<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Axioplan.GammesNomenclatures.Domain.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Axioplan.GammesNomenclatures.Domain\Axioplan.GammesNomenclatures.Domain.csproj" />
    <ProjectReference Include="..\..\src\Axioplan.GammesNomenclatures.Application\Axioplan.GammesNomenclatures.Application.csproj" />
    <ProjectReference Include="..\..\src\Axioplan.GammesNomenclatures.Infrastructure\Axioplan.GammesNomenclatures.Infrastructure.csproj" />
  </ItemGroup>

</Project>
